window.APP_LANGS = window.APP_LANGS || {};
window.APP_LANGS.en = {
  from: 'From',
  to: 'To',
  findTicket: 'Find Ticket',
  welcome: 'Welcome',
  signIn: 'Sign In',
  register: 'Register',
  signInTitle: 'Sign in to continue',
  signInSub: 'Access your bookings, boarding pass and offline travel details.',
  registerTitle: 'Create your travel account',
  registerSub: 'Save your details once and move faster through every check-in.',
  firstName: 'First name',
  lastName: 'Last name',
  phone: 'Phone',
  email: 'Email',
  password: 'Password',
  continueGoogle: 'Continue with Google',
  createAccount: 'Create account',
  accountCreated: 'Account created. Your profile is ready.',
  signedGoogle: 'Signed in with Google.',
  signedInSuccess: 'Signed in successfully.',
  bookingLookup: 'Booking Lookup',
  retrieveBooking: 'Retrieve booking',
  checkInJourney: 'Check-in journey',
  findYourBooking: 'Find your booking',
  lookupSub: 'Enter your booking reference and last name to display your itinerary and current check-in status.',
  bookingRef: 'Booking reference',
  departure: 'Departure',
  duration: 'Duration',
  passenger: 'Passenger',
  seeFlights: 'See Flights',
  startCheckIn: 'Start Check-In',
  flights: 'Flights',
  date: 'Date',
  price: 'Price',
  selectFlight: 'Select flight',
  onlineCheckIn: 'Online Check-In',
  passport: 'Passport',
  review: 'Review',
  seat: 'Seat',
  bags: 'Bags',
  requests: 'Requests',
  passportScan: 'Passport Scan',
  passportSub: 'Scan the first page of the passport and verify the extracted identity details before check-in.',
  uploadPassport: 'No passport scan uploaded yet',
  uploadScan: 'Upload scan',
  simulateOcr: 'Run OCR',
  passportNumber: 'Passport number',
  nationality: 'Nationality',
  ocrVerify: 'The OCR result should match the booking details before continuing.',
  cancel: 'Cancel',
  continue: 'Continue',
  detailsReview: 'Details Review',
  reviewSub: 'Review the passenger identity and travel data before confirming.',
  flight: 'Flight',
  confirmDetails: 'Confirm all details',
  confirmDetailsSub: 'I confirm the identity and travel information are correct.',
  back: 'Back',
  seatSelection: 'Seat Selection',
  seatSub: 'Choose an available seat. Premium seats are highlighted separately.',
  deckPlan: 'Interactive seat map',
  selectedSeat: 'Selected seat',
  available: 'Available',
  occupied: 'Occupied',
  premium: 'Premium',
  selected: 'Selected',
  baggageDeclaration: 'Baggage Declaration',
  bagsSub: 'Declare the number of cabin and checked bags before generating the boarding pass.',
  cabinBag: 'Cabin bags',
  checkedBag: 'Checked bags',
  bagNote: 'Your baggage summary is included in the local trip record and can be synced when online.',
  specialRequests: 'Special Requests',
  requestsSub: 'Set meal preference and declare assistance, infant or pet travel requirements.',
  mealPreference: 'Meal preference',
  specialAssistance: 'Special assistance',
  assistanceSub: 'Wheelchair or airport support request',
  infant: 'Traveling with infant',
  infantSub: 'Declare an infant traveler for your booking',
  pet: 'Traveling with pet',
  petSub: 'Declare a pet for airline handling procedures',
  additionalNotes: 'Additional notes',
  notesPlaceholder: 'Special instructions or comments',
  completionNote: 'A confirmation notification will be shown once check-in is completed.',
  completeCheckIn: 'Complete Check-In',
  boardingPass: 'Boarding Pass',
  readyToBoard: 'Ready to board',
  class: 'Class',
  terminal: 'Terminal',
  gate: 'Gate',
  offlineAccessText: 'Your boarding pass and flight summary are saved locally for offline access.',
  downloadPdf: 'Download PDF',
  syncNow: 'Sync now',
  profile: 'Profile',
  edit: 'Edit',
  offlineReady: 'Offline ready',
  syncEnabled: 'Auto-sync enabled',
  travelPreferences: 'Travel preferences',
  change: 'Change',
  toggle: 'Toggle',
  appSettings: 'App settings',
  language: 'Language',
  switchLang: 'Switch',
  cacheStatus: 'Offline cache',
  storedLocally: 'Stored locally on device',
  clear: 'Clear',
  navHome: 'Home',
  navLookup: 'Lookup',
  navFlights: 'Flights',
  navPass: 'Pass',
  navProfile: 'Profile',
  passengers: 'Passengers',
  economy: 'Economy',
  english: 'English',
  french: 'French',
  enabled: 'Enabled',
  none: 'None',
  homeCountry: 'Australia',
  heroCity: 'Sydney',
  synced: 'Synced',
  syncToastBody: 'Latest updates are now available offline.',
  bookingFound: 'Booking found',
  itineraryLoaded: 'Your itinerary is ready.',
  bookingNotFound: 'Booking not found',
  checkReference: 'Check the booking reference and last name.',
  checkinOpen: 'Check-in Open',
  flightSelected: 'Flight selected',
  bookingReady: 'Booking details loaded for check-in.',
  ocrComplete: 'OCR complete',
  identityVerified: 'Identity fields were extracted successfully.',
  passportNeeded: 'Passport scan required',
  scanFirst: 'Upload or scan the passport first.',
  confirmRequired: 'Confirmation required',
  confirmBeforeContinue: 'Please confirm the details before moving on.',
  checkinComplete: 'Check-in complete',
  boardingPassReady: 'Your digital boarding pass is ready.',
  pdfReady: 'PDF export ready',
  printDialogInfo: 'Use your browser print dialog to save the boarding pass as PDF.',
  languageUpdated: 'Language updated',
  languageApplied: 'The interface language has been changed.',
  cacheCleared: 'Cache cleared',
  localDataRemoved: 'Saved local booking data has been removed.',
  connected: 'Connected',
  offlineMode: 'Offline mode',
  usingCachedData: 'Using saved boarding pass and cached flight details.'
};
