window.APP_LANGS = window.APP_LANGS || {};
window.APP_LANGS.fr = {
  from: 'Départ',
  to: 'Arrivée',
  findTicket: 'Trouver le vol',
  welcome: 'Bienvenue',
  signIn: 'Connexion',
  register: 'Inscription',
  signInTitle: 'Connectez-vous pour continuer',
  signInSub: 'Accédez à vos réservations, votre carte d’embarquement et vos données hors ligne.',
  registerTitle: 'Créez votre compte voyage',
  registerSub: 'Enregistrez vos informations une seule fois pour accélérer chaque enregistrement.',
  firstName: 'Prénom',
  lastName: 'Nom',
  phone: 'Téléphone',
  email: 'E-mail',
  password: 'Mot de passe',
  continueGoogle: 'Continuer avec Google',
  createAccount: 'Créer un compte',
  accountCreated: 'Compte créé. Votre profil est prêt.',
  signedGoogle: 'Connexion via Google réussie.',
  signedInSuccess: 'Connexion réussie.',
  bookingLookup: 'Recherche de réservation',
  retrieveBooking: 'Retrouver la réservation',
  checkInJourney: 'Parcours d’enregistrement',
  findYourBooking: 'Retrouvez votre réservation',
  lookupSub: 'Entrez votre référence de réservation et votre nom pour afficher l’itinéraire et le statut d’enregistrement.',
  bookingRef: 'Référence de réservation',
  departure: 'Départ',
  duration: 'Durée',
  passenger: 'Passager',
  seeFlights: 'Voir les vols',
  startCheckIn: 'Commencer',
  flights: 'Vols',
  date: 'Date',
  price: 'Prix',
  selectFlight: 'Choisir ce vol',
  onlineCheckIn: 'Enregistrement en ligne',
  passport: 'Passeport',
  review: 'Vérification',
  seat: 'Siège',
  bags: 'Bagages',
  requests: 'Demandes',
  passportScan: 'Scan du passeport',
  passportSub: 'Scannez la première page du passeport et vérifiez les informations extraites avant l’enregistrement.',
  uploadPassport: 'Aucun scan de passeport ajouté',
  uploadScan: 'Ajouter un scan',
  simulateOcr: 'Lancer l’OCR',
  passportNumber: 'Numéro du passeport',
  nationality: 'Nationalité',
  ocrVerify: 'Le résultat OCR doit correspondre aux informations de réservation avant de continuer.',
  cancel: 'Annuler',
  continue: 'Continuer',
  detailsReview: 'Vérification des données',
  reviewSub: 'Vérifiez les informations du passager et du voyage avant confirmation.',
  flight: 'Vol',
  confirmDetails: 'Confirmer les informations',
  confirmDetailsSub: 'Je confirme que les informations d’identité et de voyage sont correctes.',
  back: 'Retour',
  seatSelection: 'Choix du siège',
  seatSub: 'Choisissez un siège disponible. Les sièges premium sont indiqués séparément.',
  deckPlan: 'Plan interactif de la cabine',
  selectedSeat: 'Siège choisi',
  available: 'Disponible',
  occupied: 'Occupé',
  premium: 'Premium',
  selected: 'Sélectionné',
  baggageDeclaration: 'Déclaration des bagages',
  bagsSub: 'Déclarez le nombre de bagages cabine et soute avant la carte d’embarquement.',
  cabinBag: 'Bagages cabine',
  checkedBag: 'Bagages en soute',
  bagNote: 'Le résumé des bagages est conservé localement et peut être synchronisé en ligne.',
  specialRequests: 'Demandes spéciales',
  requestsSub: 'Définissez le repas et déclarez assistance, nourrisson ou animal.',
  mealPreference: 'Préférence repas',
  specialAssistance: 'Assistance spéciale',
  assistanceSub: 'Demande d’accompagnement ou fauteuil roulant',
  infant: 'Voyage avec nourrisson',
  infantSub: 'Déclarer un nourrisson pour cette réservation',
  pet: 'Voyage avec animal',
  petSub: 'Déclarer un animal pour la prise en charge compagnie',
  additionalNotes: 'Notes complémentaires',
  notesPlaceholder: 'Instructions ou remarques particulières',
  completionNote: 'Une notification de confirmation s’affiche une fois l’enregistrement terminé.',
  completeCheckIn: 'Terminer l’enregistrement',
  boardingPass: 'Carte d’embarquement',
  readyToBoard: 'Prêt à embarquer',
  class: 'Classe',
  terminal: 'Terminal',
  gate: 'Porte',
  offlineAccessText: 'Votre carte d’embarquement et le résumé du vol sont enregistrés localement hors ligne.',
  downloadPdf: 'Télécharger en PDF',
  syncNow: 'Synchroniser',
  profile: 'Profil',
  edit: 'Modifier',
  offlineReady: 'Hors ligne prêt',
  syncEnabled: 'Synchronisation active',
  travelPreferences: 'Préférences voyage',
  change: 'Changer',
  toggle: 'Activer',
  appSettings: 'Réglages de l’app',
  language: 'Langue',
  switchLang: 'Basculer',
  cacheStatus: 'Cache hors ligne',
  storedLocally: 'Enregistré localement sur l’appareil',
  clear: 'Vider',
  navHome: 'Accueil',
  navLookup: 'Recherche',
  navFlights: 'Vols',
  navPass: 'Carte',
  navProfile: 'Profil',
  passengers: 'Passagers',
  economy: 'Économique',
  english: 'Anglais',
  french: 'Français',
  enabled: 'Activée',
  none: 'Aucune',
  homeCountry: 'Australie',
  heroCity: 'Sydney',
  synced: 'Synchronisé',
  syncToastBody: 'Les dernières mises à jour sont maintenant disponibles hors ligne.',
  bookingFound: 'Réservation trouvée',
  itineraryLoaded: 'Votre itinéraire est prêt.',
  bookingNotFound: 'Réservation introuvable',
  checkReference: 'Vérifiez la référence et le nom.',
  checkinOpen: 'Enregistrement ouvert',
  flightSelected: 'Vol sélectionné',
  bookingReady: 'Les détails du vol sont prêts pour l’enregistrement.',
  ocrComplete: 'OCR terminé',
  identityVerified: 'Les champs d’identité ont été extraits avec succès.',
  passportNeeded: 'Passeport requis',
  scanFirst: 'Ajoutez ou scannez d’abord le passeport.',
  confirmRequired: 'Confirmation requise',
  confirmBeforeContinue: 'Merci de confirmer les informations avant de continuer.',
  checkinComplete: 'Enregistrement terminé',
  boardingPassReady: 'Votre carte d’embarquement digitale est prête.',
  pdfReady: 'Export PDF prêt',
  printDialogInfo: 'Utilisez la boîte d’impression du navigateur pour enregistrer la carte en PDF.',
  languageUpdated: 'Langue mise à jour',
  languageApplied: 'La langue de l’interface a été modifiée.',
  cacheCleared: 'Cache vidé',
  localDataRemoved: 'Les données locales enregistrées ont été supprimées.',
  connected: 'Connecté',
  offlineMode: 'Mode hors ligne',
  usingCachedData: 'Utilisation de la carte enregistrée et des données de vol en cache.'
};
